### ISSUE TITLE
remove a dependency

### ISSUE THREAD

**Issue by freeman-lab** [jasminetstone/fakearray#1]
I think in this bit https://github.com/jasminetstone/fakearray/blob/master/fakearray/calciumimaging.py#L73 we should just return an array, i.e. the result of calling `numpy.asarray(frames)`. That way, we remove any `thunder` dependency, and moving forward, we can keep a consistent API of always returning just arrays, which matches the package name 😄

**Comment by syncrostone** [comment]
Done!
